# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: namm_po.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "NammStandards.NammPoData" do
    optional :id, :string, 1
    optional :timestamp, :string, 2
    optional :header, :message, 10, "NammStandards.PoHeaderData"
    optional :detail, :message, 11, "NammStandards.PoDetailData"
  end
  add_message "NammStandards.PoHeaderData" do
    optional :buyer_order_id, :string, 1
    optional :ship_instructions, :string, 2
    optional :bill_to, :message, 10, "NammStandards.PartyData"
    optional :ship_to, :message, 11, "NammStandards.PartyData"
    optional :sold_to, :message, 12, "NammStandards.PartyData"
    optional :supplier, :message, 13, "NammStandards.PartyData"
    optional :terms, :message, 14, "NammStandards.TermsData"
  end
  add_message "NammStandards.PoDetailData" do
    repeated :items, :message, 10, "NammStandards.ItemData"
  end
  add_message "NammStandards.AddressData" do
    optional :attn, :string, 1
    optional :address_1, :string, 2
    optional :address_2, :string, 3
    optional :address_3, :string, 4
    optional :city, :string, 5
    optional :state, :string, 6
    optional :postal_code, :string, 7
    optional :country, :string, 8
    optional :country_code, :string, 9
  end
  add_message "NammStandards.ItemData" do
    optional :buyer_item_id, :string, 1
    optional :buyer_item_desc, :string, 2
    optional :quantity, :message, 10, "NammStandards.QuantityData"
    optional :ship_to, :message, 11, "NammStandards.PartyData"
  end
  add_message "NammStandards.PartyData" do
    optional :party_id, :string, 1
    optional :name, :string, 2
    optional :address, :message, 10, "NammStandards.AddressData"
  end
  add_message "NammStandards.TermsData" do
    optional :code, :enum, 1, "NammStandards.TermCode"
    optional :date, :string, 2
    optional :days, :int32, 3
    optional :percent, :int32, 4
    optional :percent_days, :int32, 5
  end
  add_message "NammStandards.QuantityData" do
    optional :units, :int32, 1
    optional :units_of_measure, :enum, 2, "NammStandards.QuantityUOM"
  end
  add_enum "NammStandards.TermCode" do
    value :TermCodeUndefined, 0
    value :P001, 1
    value :P002, 2
    value :P003, 3
  end
  add_enum "NammStandards.QuantityUOM" do
    value :QuantityUOMUndefined, 0
    value :BAG, 1
    value :BKT, 2
    value :BND, 3
    value :BOWL, 4
    value :BX, 5
    value :CRD, 6
    value :CM, 7
    value :CS, 8
    value :CTN, 9
    value :DZ, 10
    value :EA, 11
  end
end

module NammStandards
  NammPoData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.NammPoData").msgclass
  PoHeaderData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.PoHeaderData").msgclass
  PoDetailData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.PoDetailData").msgclass
  AddressData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.AddressData").msgclass
  ItemData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.ItemData").msgclass
  PartyData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.PartyData").msgclass
  TermsData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.TermsData").msgclass
  QuantityData = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.QuantityData").msgclass
  TermCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.TermCode").enummodule
  QuantityUOM = Google::Protobuf::DescriptorPool.generated_pool.lookup("NammStandards.QuantityUOM").enummodule
end
